/**
 * ──────────────────────────────────────────────────────────────────────────
 *  Core domain types for the CLAR Evaluator.
 *  These are the contracts referenced throughout the app: Rubric, Criterion,
 *  Check, StudentResult, RaaSActivity.
 * ──────────────────────────────────────────────────────────────────────────
 */

/** A single boolean test that contributes to a criterion's score. */
export interface Check {
  /** Did the test pass? */
  pass: boolean;
  /** Human-readable description shown in the UI. */
  label: string;
  /** First matching evidence snippet, or null when nothing matched. */
  found: string | null;
}

/** The result of running one criterion's evaluator against a CLAR text. */
export interface CriterionResult {
  /** Numeric score in [0, criterion.max]. */
  score: number;
  /** Per-check breakdown surfaced in the detail view. */
  checks: Check[];
  /** True when auto-scoring is unreliable and a grader must set the score (ISU). */
  requiresManualScoring?: boolean;
  /** Informational readiness hint (e.g. "3/4 structural checks passed"). */
  readinessHint?: string;
  /** Tenant-side verification note shown to the grader. */
  tenantNote?: string;
}

/** ISSG criterion is pass/partial/fail (no numeric score). */
export interface IssgResult {
  status: "pass" | "partial" | "fail" | "na";
  note: string;
}

/** Match mode for a data-driven check parsed from rule documents. */
export type CheckMode = "has" | "count";

/**
 * A data-driven check: regex pattern(s) evaluated against the CLAR text.
 * Used for criteria parsed from rule documents (no code change required to add).
 */
export interface DataCheck {
  id: string;
  label: string;
  /** Regex source strings (case-insensitive). Any match => present. */
  patterns: string[];
  mode: CheckMode;
  /** For mode "count": minimum occurrences required to pass (default 1). */
  threshold?: number;
}

/** Keys of the built-in (ported 1:1) evaluators. */
export type BuiltinEvaluatorKey =
  | "arrangement"
  | "swimlanes"
  | "error_handler"
  | "send_error"
  | "naming_integration"
  | "core_logic"
  | "naming_components"
  | "no_logs"
  | "cloud_log"
  | "isu";

/**
 * A rubric criterion. `kind` distinguishes the ported built-in evaluators
 * (regex logic preserved exactly) from data-driven criteria generated by the
 * rule-document parser. Both expose an editable `max` (weight).
 */
export interface Criterion {
  id: string;
  label: string;
  /** Editable weight / max score. */
  max: number;
  /** The max this criterion shipped with — used to scale built-in scores when the grader edits `max`. */
  defaultMax: number;
  subItems?: string[];
  kind: "builtin" | "data-driven" | "issg";
  /** Present when kind === "builtin". */
  evaluatorKey?: BuiltinEvaluatorKey;
  /** Present when kind === "data-driven". */
  checks?: DataCheck[];
  /** True when this criterion always requires manual scoring (auto-score 0). */
  manual?: boolean;
  /** True for the 0-point ISSG tenant check. */
  scoreless?: boolean;
  /** Origin label shown in the editor, e.g. "default" or "rules.docx". */
  source?: string;
}

/** A complete, editable rubric. */
export interface Rubric {
  criteria: Criterion[];
}

/** Output of evaluating one CLAR text against a rubric. */
export interface EvaluationOutput {
  results: Record<string, CriterionResult>;
  issg: IssgResult;
  observations: string[];
  remark: string;
  total: number;
  pct: number;
}

/** A student's full evaluation record (single or batch). */
export interface StudentResult extends EvaluationOutput {
  /** Stable id (filename-derived). */
  id: string;
  /** Display name (filename without extension). */
  name: string;
  fileName: string;
  status: "pending" | "reading" | "done" | "error";
  error?: string;
  /** Grader overrides keyed by criterion id. */
  manualScores: Record<string, number>;
  /** Matched RAAS activity, if a RAAS report was fetched. */
  raas?: RaaSActivity | null;
  /** RAAS-verified ISU attachment for this CLAR's integration, if checked. */
  isuAttachment?: IsuAttachment | null;
}

/**
 * Result of looking up — via a RAAS Integration-System report — whether the
 * integration named by a CLAR file is attached to an ISU (Workday_Account).
 */
export interface IsuAttachment {
  /** Integration name used as the report prompt (CLAR filename without .clar). */
  integrationName: string;
  /** True only when a lookup actually completed (vs. skipped/errored). */
  checked: boolean;
  /** True when the report returned a non-empty Workday_Account. */
  attached: boolean;
  /** The ISU the integration is tagged to, or null when not attached. */
  workdayAccount: string | null;
  /** Workday's "Integration_System" value, when present. */
  integrationSystem?: string;
  /** Workday's "System_Name" value, when present. */
  systemName?: string;
  /** Workday's "referenceID" value, when present. */
  referenceId?: string;
  /** Set when the lookup could not be performed (config/network/auth). */
  error?: string;
}

/** Response shape from POST /api/raas/integration. */
export interface RaaSIntegrationResponse {
  ok: boolean;
  attached: boolean;
  workdayAccount: string | null;
  integrationSystem?: string;
  systemName?: string;
  referenceId?: string;
  format?: "json" | "xml";
  error?: string;
}

/** Normalized Workday RAAS user-activity row mapped to a student. */
export interface RaaSActivity {
  /** The key we matched on (username or normalized name). */
  matchedKey: string;
  displayName?: string;
  username?: string;
  /** Number of sign-ons / sessions, when present in an aggregated report. */
  signOns?: number;
  /** Last activity timestamp string as returned by the report. */
  lastActivity?: string;
  /** Total tasks / events count, when present in an aggregated report. */
  totalTasks?: number;

  // ── Event-level fields (a User Activity report is one row per action) ──
  /** Raw "System Account" value, e.g. "mgupta-trn / Monika Gupta". */
  systemAccount?: string;
  /** The Workday task performed, e.g. "View Cloud Collection (Studio Project)". */
  task?: string;
  /** The object acted on, e.g. the downloaded "SN_STUDIO_GHP_EXAM1.clar". */
  target?: string;
  /** Activity category, e.g. "DOWNLOAD". */
  activityCategory?: string;
  /** When the activity happened (report's Request Time). */
  requestTime?: string;
  /** Source IP address of the request. */
  ipAddress?: string;

  /** The raw report row, for fields not covered by the normalized shape. */
  raw: Record<string, unknown>;
}

/**
 * A single download/copy event extracted from the activity report — the unit
 * used to track who downloaded a Studio CLAR (potential copying). One per
 * matching row (Activity Category = DOWNLOAD + Task = View Cloud Collection).
 */
export interface DownloadEvent {
  /** Best display label for the actor (display name, else username, else account). */
  downloader: string;
  username?: string;
  displayName?: string;
  /** The CLAR / Studio project that was downloaded. */
  target?: string;
  task?: string;
  activityCategory?: string;
  requestTime?: string;
  ipAddress?: string;
  /** True when the downloaded target does not appear to belong to the downloader. */
  crossAccount: boolean;
}

/** Field-name mapping so the grader can adapt to their report's column names. */
export interface RaaSFieldMap {
  username: string;
  displayName: string;
  signOns?: string;
  lastActivity?: string;
  totalTasks?: string;
}

/** Response shape from POST /api/raas. */
export interface RaaSResponse {
  ok: boolean;
  rows: RaaSActivity[];
  count: number;
  format: "json" | "xml";
  error?: string;
}
